const roles=["研发负责人","知识产权人员","生物医药研发人员"];
const industries=["半导体与集成电路","新能源与汽车","高端装备与制造","新材料与化工","生物医药与大健康","消费电子"];
const stages=["技术预研","研发立项","技术攻关","专利申请","风险管理","成果转化"];
const hotspots=[
 {id:1,industry:"新能源与汽车",title:"固态电池产业化进程持续加速",fact:"头部企业密集发布量产时间表，材料体系与工艺路线仍存在分化。",role:"研发负责人",pain:"路线选择缺少证据，担心投入后技术路线被淘汰",impact:"研发立项与路线决策",skills:["technology-insight-analysis","patent-project-proposal","tech-evolution-analysis"],hook:"《固态电池技术路线初筛报告》",score:96},
 {id:2,industry:"半导体与集成电路",title:"AI芯片供应链与先进封装成为关注焦点",fact:"算力需求推动先进封装、散热与材料方案快速演进。",role:"研发负责人",pain:"现有工程方案达到性能瓶颈，团队难以跳出本行业经验",impact:"技术攻关与跨域创新",skills:["ceae-skill","triz-functional-search","technology-insight-analysis"],hook:"《工程瓶颈根因与跨域方案清单》",score:94},
 {id:3,industry:"高端装备与制造",title:"研发降本与避免重复研发进入管理层议程",fact:"企业从单纯压缩预算转向提高立项质量和复用外部技术证据。",role:"研发负责人",pain:"无法证明项目是否重复、竞争对手是否已经领先",impact:"立项评审与研发预算",skills:["patent-research-analyst","patent-project-proposal","competitor-patent-landscape"],hook:"《研发立项重复性初筛报告》",score:93},
 {id:4,industry:"消费电子",title:"产品出海专利风险讨论升温",fact:"跨境平台合规趋严，外观与功能专利风险需要在上市前识别。",role:"知识产权人员",pain:"产品上市节奏快，人工FTO周期长且难以覆盖多国风险",impact:"上市风险与合规成本",skills:["cross-border-patent-risk-screen","generic-fto-report","patent-application-evaluation-assistant"],hook:"《出海产品专利风险自查清单》",score:91},
 {id:5,industry:"生物医药与大健康",title:"医药顶会密集披露新靶点与临床数据",fact:"大会信息密度高，管线变化、靶点热度与BD信号需要快速整合。",role:"生物医药研发人员",pain:"信息过载，难以快速判断哪些变化真正影响项目优先级",impact:"管线决策与项目立项",skills:["pharma-conference-insight-report","pharma-project-initiation-report","patsnap-lifescience-target-intelligence_zh"],hook:"《热门靶点机会与风险速览》",score:90},
 {id:6,industry:"新材料与化工",title:"绿色制造推动材料配方与催化工艺升级",fact:"双碳要求与成本压力共同推动替代材料、低能耗工艺和催化体系创新。",role:"研发负责人",pain:"性能、成本和绿色要求互相制约，缺少可验证的替代路径",impact:"配方优化与工艺创新",skills:["triz-functional-search","ceae-skill","technology-insight-analysis"],hook:"《材料工艺替代路径诊断》",score:88}
];
const outcomes=[
 {name:"看清方向",icon:"⌁",desc:"技术路线、竞争格局与演进趋势",skills:["technology-insight-analysis","tech-evolution-analysis","competitor-patent-landscape"]},
 {name:"解决技术问题",icon:"✦",desc:"根因定位、跨领域类比与创新设计",skills:["ceae-skill","triz-functional-search","innovation-radar"]},
 {name:"降低知识产权风险",icon:"◇",desc:"查新、FTO、出海与申请前评估",skills:["generic-fto-report","cross-border-patent-risk-screen","patent-application-evaluation-assistant"]},
 {name:"提高立项质量",icon:"△",desc:"避免重复研发，用证据支持GO/NO-GO",skills:["patent-project-proposal","patent-research-analyst","pharma-project-initiation-report"]},
 {name:"洞察生物医药",icon:"✚",desc:"靶点、管线、顶会与公司情报",skills:["pharma-conference-insight-report","patsnap-lifescience-target-intelligence_zh","patsnap-lifescience-company-profiling_zh"]}
];
let skillData={meta:{total:100,syncedAt:"2026-07-06"},skills:[]},activeOutcome="全部";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function loadSkills(){try{let r=await fetch("./data/skills.json",{cache:"no-store"});if(r.ok)skillData=await r.json()}catch(e){}updateSkillMeta();renderSkills()}
function updateSkillMeta(){let n=skillData.meta.total||skillData.skills.length,date=skillData.meta.syncedAt||"待首次同步";["#skillCount","#syncCount"].forEach(x=>$(x).textContent=n);$("#skillMeta").textContent=`${n} 个 Skill · ${date} 同步`;$("#syncDate").textContent=date;$("#miniSync").textContent=`${n} 个 Skill · ${date}`}
function skill(id){return skillData.skills.find(x=>x.id===id)||{id,name:id,description:"智慧芽官方 Skill，等待下一次同步补全简介。",url:`https://open.zhihuiya.com/marketplace/agent-skills/${id}`,category:"待分类"}}
function renderOverview(){ $("#opportunityGrid").innerHTML=hotspots.slice(0,3).map(h=>`<article class="op-card"><div class="op-top"><span class="tag">${h.industry}</span><b class="score">${h.score}</b></div><h3>${h.title}</h3><div class="chain"><div><span>影响用户</span><b>${h.role}</b></div><div><span>真实痛点</span><b>${h.pain}</b></div><div><span>轻解决方案</span><b>${h.skills.map(x=>skill(x).name).join(" + ")}</b></div></div><div class="hook">留资钩子：${h.hook}</div><div class="card-foot"><small>${h.impact}</small><button class="secondary generate" data-id="${h.id}">生成内容</button></div></article>`).join("")}
function renderHotspots(filter="全部"){let list=filter==="全部"?hotspots:hotspots.filter(x=>x.industry===filter);$("#hotspotList").innerHTML=list.map(h=>`<article class="hotspot-card"><div><div class="hotspot-top"><span class="tag">${h.industry}</span><b class="score">${h.score}</b></div><h3>${h.title}</h3><p>${h.fact}</p></div><div class="impact-box"><div><span>影响谁</span><b>${h.role}</b></div><div><span>引发什么问题</span><b>${h.pain}</b></div><div><span>业务影响</span><b>${h.impact}</b></div></div><button class="primary generate" data-id="${h.id}">生成方案</button></article>`).join("")}
function populate(){roles.forEach(x=>{$("#roleSelect").add(new Option(x,x));$("#contentRole").add(new Option(x,x))});industries.forEach(x=>$("#industrySelect").add(new Option(x,x)));stages.forEach(x=>$("#stageSelect").add(new Option(x,x)));hotspots.forEach(x=>$("#contentHotspot").add(new Option(x.title,x.id)));let fs=["全部",...new Set(hotspots.map(x=>x.industry))];$("#industryFilters").innerHTML=fs.map((x,i)=>`<button class="${i?"":"active"}" data-filter="${x}">${x}</button>`).join("");$("#outcomeTabs").innerHTML=["全部",...outcomes.map(x=>x.name)].map((x,i)=>`<button class="${i?"":"active"}" data-outcome="${x}">${x}</button>`).join("")}
function renderSolutions(){let list=activeOutcome==="全部"?outcomes:outcomes.filter(x=>x.name===activeOutcome);$("#solutionCards").innerHTML=list.map(o=>`<article class="solution-card"><div class="solution-icon">${o.icon}</div><div><h3>${o.name}</h3><p>${o.desc}</p><div class="skill-chips">${o.skills.map(id=>{let s=skill(id);return `<a href="${s.url}" target="_blank">${s.name}</a>`}).join("")}</div></div></article>`).join("")}
function renderSkills(q=""){let list=skillData.skills.filter(x=>(x.name+x.description+x.category).toLowerCase().includes(q.toLowerCase())).slice(0,30);$("#skillList").innerHTML=list.map(s=>`<article class="skill-item"><b>${s.name}</b><p>${s.description}</p><span class="tag">${s.category}</span></article>`).join("")||"<p>没有找到匹配 Skill</p>";renderSolutions();renderOverview()}
function inferMatch(){let role=$("#roleSelect").value,industry=$("#industrySelect").value,stage=$("#stageSelect").value,text=$("#problemInput").value.trim();let pool=hotspots.filter(x=>x.role===role);let chosen=pool.find(x=>x.industry===industry)||pool[0]||hotspots[0];let ids=[...chosen.skills],solutionName=chosen.impact,hook=chosen.hook;if(/侵权|风险|出海|FTO/i.test(text)){ids=["generic-fto-report","cross-border-patent-risk-screen","patent-application-evaluation-assistant"];solutionName="产品专利风险初筛";hook="《产品上市前专利风险自查清单》"}if(/根因|瓶颈|性能|方案/i.test(text)){ids=["ceae-skill","triz-functional-search","technology-insight-analysis"];solutionName="工程瓶颈诊断与跨域解题";hook="《工程瓶颈根因与跨域方案清单》"}if(/立项|重复|路线|竞品/i.test(text)){ids=role==="生物医药研发人员"?["pharma-project-initiation-report","patsnap-lifescience-target-intelligence_zh","technology-insight-analysis"]:["patent-project-proposal","patent-research-analyst","technology-insight-analysis"];solutionName=role==="生物医药研发人员"?"医药项目立项初筛":"研发立项重复性与路线初筛";hook=role==="生物医药研发人员"?"《药物/靶点立项机会速览》":"《研发立项重复性初筛报告》"}let pain=text||chosen.pain;$("#matchResult").className="match-result";$("#matchResult").innerHTML=`<div class="result-grid"><article class="diagnosis"><span class="live">痛点判断</span><h2>${role} · ${stage}</h2><p><b>所在行业：</b>${industry}</p><p><b>核心问题：</b>${pain}</p><p><b>浅层判断：</b>当前问题首先需要完成证据化诊断，再比较路线或风险，不建议直接跳到单一工具或结论。</p></article><article class="recommendation"><span class="live">推荐轻解决方案</span><h2>${solutionName}</h2><div class="skill-chips">${ids.map(id=>{let s=skill(id);return `<a href="${s.url}" target="_blank">${s.name}</a>`}).join("")}</div><p>${ids.map((id,i)=>`${i+1}. ${skill(id).description}`).join("<br>")}</p><div class="hook">建议留资钩子：${hook}</div><button class="primary" onclick="createDraft(${chosen.id},'${role}')">继续生成内容</button></article></div>`}
function createDraft(id,role){let h=hotspots.find(x=>x.id==id)||hotspots[0];go("content");$("#contentHotspot").value=h.id;$("#contentRole").value=role||h.role;renderDraft(h,role||h.role)}
function renderDraft(h,role){let title=`${role}别只看“${h.title}”：真正要防的是这3个决策盲区`;$("#draftResult").className="draft-result";$("#draftResult").innerHTML=`<span class="tag">事实 / 推断 / 建议已分层</span><h2>${title}</h2><div class="draft-section"><h3>01｜发生了什么</h3><p>${h.fact}</p><small>事实层：发布前需要补充并核验原始信源。</small></div><div class="draft-section"><h3>02｜为什么与你有关</h3><p>对${role}而言，这一变化真正影响的是${h.impact}。如果仍沿用旧的信息和判断框架，可能出现：${h.pain}。</p></div><div class="draft-section"><h3>03｜先问自己三个问题</h3><ol><li>现有判断是否有专利、论文、临床或市场证据支撑？</li><li>团队是否只在熟悉的技术路线中寻找答案？</li><li>是否已经明确风险边界、替代路径和下一步验证动作？</li></ol></div><div class="draft-section"><h3>04｜一个浅层解决方案</h3><p>${h.skills.map((id,i)=>`${i+1}. 用 ${skill(id).name}：${skill(id).description}`).join("<br>")}</p></div><div class="draft-section hook"><h3>留资钩子</h3><p>回复关键词“诊断”，领取${h.hook}。提交行业、角色和当前问题后，可获得一次对应场景的初步匹配。</p></div>`}
function go(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("#pageTitle").textContent={overview:"机会总览",hotspots:"行业热点",pains:"用户痛点",painRadar:"痛点 Top100",solutions:"解决方案",content:"内容工作台",leads:"线索与效果",sync:"数据与同步"}[id];scrollTo(0,0)}
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1600)}
document.addEventListener("click",e=>{let n=e.target.closest("[data-page],[data-jump]");if(n)go(n.dataset.page||n.dataset.jump);let g=e.target.closest(".generate");if(g)createDraft(+g.dataset.id);let f=e.target.closest("[data-filter]");if(f){$$("[data-filter]").forEach(x=>x.classList.remove("active"));f.classList.add("active");renderHotspots(f.dataset.filter)}let o=e.target.closest("[data-outcome]");if(o){activeOutcome=o.dataset.outcome;$$("[data-outcome]").forEach(x=>x.classList.toggle("active",x===o));renderSolutions()}});
$("#matchButton").onclick=inferMatch;$("#draftButton").onclick=()=>renderDraft(hotspots.find(x=>x.id==$("#contentHotspot").value),$("#contentRole").value);$("#skillSearch").oninput=e=>renderSkills(e.target.value);$("#globalSearch").oninput=e=>{if(e.target.value.trim()){go("solutions");$("#skillSearch").value=e.target.value;renderSkills(e.target.value)}};
populate();renderHotspots();renderOverview();renderSolutions();loadSkills();
